directories:
  gal_zoo: "data/GalaxyZoo1_DR_table2.csv.gz"
  ref_table: "data/gz2_filename_mapping.csv"
  labels: "data/labels.csv"
  images: "data/images/"
  train_dir: "data/train"
  test_dir: "data/test"
  validate_dir: "data/validate"
data:
  train_split: 0.6
  test_split: 0.2